### ISSUE TITLE
PROD support for`nextcloud` module

### ISSUE THREAD

**Issue by euroblaze** [euroblaze/nextcloud#11]
Production support on ecoTEST, InnproTEST and corresponding live servers. 

Coming up… 
- Connect and test with Nextcloud server. 
- stress-test with **large files**. 
- Optimize **Nginx performance**. 
- Optimize **data management** between local odoo server and remote nextcloud server.
- manage Odoo server file storage outside of the **docker**. 
- Architect **storage mapping** between Odoo modules, and Nextcloud folders
- provide **production** support.
- **integration** with other modules, and **stability** thereof.

**Comment by VTV24710** [comment]
Hello @euroblaze , this issue I estimate 1hr but if there is any issue in database can you give me bonus 1hr - 2hr more to fix the error?

**Comment by euroblaze** [comment]
> this issue I estimate 1hr but if there is any issue in database can you give me bonus 1hr - 2hr more to fix the error?

Installing the module is no problem. I can do it myself. There are going to be some bugs and some enhancements required so this is just to get things warmed up for what's to come. 


Approving 1.5h to fix the mentioned error on demo, deploy and connect with NC. 

Coming up… 
- Connect and test with Nextcloud server. 
- stress-test with **large files**. 
- Optimize **Nginx performance**. 
- Optimize **data management** between local odoo server and remote nextcloud server.
- manage Odoo server file storage outside of the **docker**. 
- Architect **storage mapping** between Odoo modules, and Nextcloud folders
- provide **production** support.
- **integration** with other modules, and **stability** thereof.

@VTV24710

**Comment by euroblaze** [comment]
Trying to Uninstall, throws this error:
```
Record does not exist or has been deleted.
(Record: ir.model.fields(7478,), User: 1)
```

Now all of a sudden, going to Settings > Users & Companies > Company, this error appears..
```
...
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3216, in read
    raise ValueError("Invalid field %r on model %r" % (name, self._name))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Invalid field 'nextcloud_url' on model 'res.company'
```

@VTV24710

**Comment by euroblaze** [comment]
@VTV24710 

## Rescue Setup

`ssh poweron@innpro-repair.poweron.software -v` (Vy Vo key is installed)
https://innpro-repair.poweron.software/web/login

`sudo` available for `docker` and `service` commands. `erpPower!`

After freshly restarting docker and nginx and [reloading browser login page](https://innpro-repair.poweron.software/web/login):

```
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 90, in check
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 311, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UndefinedColumn: column ir_attachment.nextcloud_folder_id does not exist
LINE 1: ..."nextcloud_share_link" as "nextcloud_share_link", "ir_attach...
                                                             ^ - - -
```
---
## odoo.sql_db: Connection to the database failed
odoo@1491282e70d9:~$ tail -f /var/log/odoo/odoo-server.log 
2024-02-15 07:39:01,118 19 WARNING poweron_prod odoo.fields: project.project.last_update_status: selection=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('off_track', 'Off Track'), ('on_hold', 'On Hold'), ('1', 'No Material and No Manpower'), ('2', 'Material and No Manpower'), ('3', 'No Material and Manpower'), ('4', 'Material and Manpower')] overrides existing selection; use selection_add instead 
2024-02-15 07:39:01,283 19 INFO poweron_prod odoo.modules.loading: Modules loaded. 
2024-02-15 07:39:01,308 19 INFO poweron_prod odoo.modules.registry: Registry loaded in 1.384s 
2024-02-15 07:39:01,328 19 INFO poweron_prod odoo.addons.base.models.ir_cron: Starting job `payment: post-process transactions`. 
2024-02-15 07:39:01,337 19 INFO poweron_prod odoo.addons.base.models.ir_cron: Job `payment: post-process transactions` done. 
2024-02-15 07:46:08,429 41 INFO ? odoo: Odoo version 15.0-20230908 
2024-02-15 07:46:08,430 41 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf 
2024-02-15 07:46:08,430 41 INFO ? odoo: addons paths: ['/usr/lib/python3/dist-packages/odoo/addons', '/var/lib/odoo/.local/share/Odoo/addons/15.0', '/mnt/extra-addons', '/mnt/oca_collection/odoo-formio', '/mnt/oca_collection/helpdesk', '/mnt/oca_collection/server-brand', '/mnt/oca_collection/server-ux', '/mnt/3p_collection', '/mnt/oca_collection/partner-contact'] 
2024-02-15 07:46:08,430 41 INFO ? odoo: database: default@default:default 
2024-02-15 07:46:08,431 41 INFO ? odoo.sql_db: Connection to the database failed 

---
## LLM Analysis
The error message you're encountering indicates that there's an issue with your Odoo database schema: a column expected by Odoo or one of its modules (`ir_attachment.nextcloud_folder_id`) does not exist in the database. This can happen for several reasons, typically related to module installation, upgrade, or customization:

Database name on Docker: `poweron_prod`.

### Causes

1. **Module Upgrade or Installation**: If you've recently upgraded an Odoo module or installed a new one that interacts with the `ir_attachment` model (possibly a module related to integrating Nextcloud), the database schema may not have been updated correctly to include the new column.

2. **Partial or Failed Installation/Upgrade**: The module installation or upgrade process may have been interrupted or failed, resulting in an incomplete database schema update.

3. **Custom Module**: If this column is part of a custom module or third-party module that integrates Odoo with Nextcloud, ensure that the module is correctly installed and that all its dependencies are met.

### Solutions

1. **Update Module List and Upgrade Module**:
    - Make sure Odoo is aware of all available modules and their latest versions. You can update the module list from the Odoo UI (Settings > Update Apps List) or via command line inside your Docker container:
      ```bash
      odoo -u base -d your_database_name --stop-after-init
      ```
    - After updating the module list, try upgrading the module that adds the `nextcloud_folder_id` column to the `ir_attachment` model. This can be done from the Odoo UI or via the command line by specifying the module name instead of `base`.

2. **Check Module Installation**:
    - Ensure that the module responsible for adding the `nextcloud_folder_id` column is correctly installed. You might need to reinstall or update the module if the installation was incomplete.

3. **Manual Database Update** (Advanced):
    - If you're familiar with PostgreSQL and understand the implications, you can manually add the missing column to the `ir_attachment` table in your database. This approach is risky and should only be done with a full understanding of the database schema and a backup in place.
      ```sql
      ALTER TABLE ir_attachment ADD COLUMN nextcloud_folder_id integer;
      ```
      Note: Replace `integer` with the correct data type based on what the module expects for this column.

4. **Restore From Backup**:
    - If the issue arose after a failed upgrade or installation and cannot be resolved easily, consider restoring from a backup taken before the operation.

5. **Check for Module Bugs or Documentation**:
    - If you're using a third-party module for Nextcloud integration, check the module's documentation or issue tracker for known issues or upgrade steps you might have missed.

### Important Notes

- Always backup your database before attempting manual fixes or significant operations like module upgrades.
- Ensure your Odoo and all related modules are compatible with the version of Odoo you're running.
- If the issue persists, consider reaching out for support on Odoo forums or from the module developers.

**Comment by euroblaze** [comment]
@VTV24710 

`git reset –hard 5dae79943d9768f4403df733bb56b57ed56a6d79`

```
git log
commit 5dae79943d9768f4403df733bb56b57ed56a6d79 (HEAD -> demo)
Author: Simplify-ERP<E2><84><A2> <github@euroblaze.de>
Date:   Fri Jun 23 08:10:12 2023 +0200
```

> You try to upgrade the module nextcloud that depends on the module: documents.
> But this module is not available in your system.
